# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('birthYear', models.IntegerField()),
                ('birthPlace', models.TextField(max_length=50)),
                ('biography', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.TextField(max_length=50)),
                ('name', models.TextField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('genre', models.CharField(choices=[('comedy', 'comedy'), ('action', 'action'), ('drama', 'drama'), ('terror', 'terror'), ('fantasy', 'fantasy'), ('thriller', 'thriller'), ('aventura', 'aventura'), ('scienceFiction', 'scienceFiction'), ('western', 'western')], max_length=15, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actors', models.ManyToManyField(to='Videoteca.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Videoteca',
            fields=[
                ('client', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Videoteca.Client')),
                ('data_lloguer', models.DateField()),
                ('data_limit', models.DateField()),
                ('movies', models.ManyToManyField(to='Videoteca.Movie')),
            ],
        ),
    ]
