# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videoteca', '0002_auto_20170420_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoteca',
            name='movies',
            field=models.ManyToManyField(null=True, related_name='films', to='Videoteca.Movie'),
        ),
    ]
